# Generated by Django 4.2.13 on 2024-07-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20240626_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='otp',
            new_name='otc',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='otp_expiry',
            new_name='otc_expiry',
        ),
    ]
