# Generated by Django 4.2.13 on 2024-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_country_name_alter_country_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_id',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
    ]
