# Generated by Django 4.2.13 on 2024-07-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_plan_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.CharField(blank=True, default='USDT(BEP20)', max_length=10, null=True),
        ),
    ]
