# Generated by Django 4.2.13 on 2024-07-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_withdrawalapplication_wallet_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingdeposit',
            name='payment_proof',
        ),
        migrations.AddField(
            model_name='pendingdeposit',
            name='deposit_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
