# Generated by Django 4.2.13 on 2024-09-12 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0019_remove_pendingdeposit_payment_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_start', models.DateTimeField(null=True)),
                ('plan_end', models.DateTimeField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='withdrawalapplication',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['cost']},
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='allow_automatic_investment',
            new_name='allow_automatic_subscription',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_cost',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='min_cost',
        ),
        migrations.AddField(
            model_name='plan',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cost of the plan, currency is USD', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.CharField(choices=[('vip', 'vip'), ('vvip', 'vvip')], max_length=40),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('30', 'Monthly'), ('120', 'Quarterly'), ('365', 'Annually'), ('730', 'Biannually'), ('3650', 'Lifetime')], max_length=30),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(help_text='name you wish to call the  plan', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('BONUS', 'BONUS'), ('AIR DROP', 'AIR DROP'), ('REFERAL EARNING', 'REFERAL EARNING')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='WithdrawalApplication',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_subscription', to='wallet.plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
