# Generated by Django 4.2.13 on 2024-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_subscription_remove_withdrawalapplication_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.PositiveIntegerField(choices=[(30, 'Monthly'), (120, 'Quarterly'), (365, 'Annually'), (730, 'Biannually'), (3650, 'Lifetime')]),
        ),
    ]
