# Generated by Django 4.2.13 on 2024-09-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_alter_plan_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VIP PROFITABLE ZONE', 'VIP PROFITABLE ZONE'), ('VVIP BULLIGON SIGNALS', 'VVIP BULLIGON SIGNALS')], max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='category',
        ),
    ]
