# Generated by Django 4.2.13 on 2024-09-22 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_plancategory_remove_plan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='wallet.plancategory'),
        ),
    ]
