# Generated by Django 4.2.13 on 2024-09-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_plan_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='cat',
            new_name='category',
        ),
    ]
