# Generated by Django 4.2.13 on 2024-09-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_rename_cat_plan_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=50)),
                ('signal_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], max_length=4)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('take_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=7)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('exclude_for', models.ManyToManyField(blank=True, to='wallet.plancategory')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
