# Generated by Django 4.2.13 on 2024-09-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_signal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancategory',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='plancategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
